phrase:
  access_token: 96f02140188b126365d27ac944bc9ca9b18da4a8b224168fe8c5196794fa0f13
  project_id: addc1b7211721d8c871c10f68d97fed4
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: simple_json
